[build]
  base = "frontend"
  publish = "out"
  command = "yarn build"
  ignore = "exit 0"  # Skip git-triggered builds; deploys must be triggered via deploy hook to ensure the production Strapi site is up and running

[build.environment]
  NODE_VERSION = "20"

[context.branch-deploy]
  command = "echo 'Branch deploys disabled' && exit 0"
